---
- name: Demo on variables
  hosts: all
  ##declaring variable on Play-level
  vars:
    URL1: play.google.com
  vars_files:
    - vars_file
  tasks:
    - name: Print variable on Play level
      debug:
        msg: URL: "{{URL1}}"
    - name: Print variable from file level
      debug:
        msg: URL: "{{URL2}}"
    - name: Print variable on task level
      vars: URL3: tasks.google.com
      debug:
        msg: URL: "{{URL3}}"

    - name: Print variable from inventory/host file
      debug:
        msg: URL: "{{URL4}}"

